server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DylanVallejo/kruger-full-stack-backend
          searchPaths: config-data        


  application:
    name: config-microservice
